version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/iso_back
    ports:
      - 8020:8020
    image: app:iso_back
    container_name: iso_back_container
    command: >
      sh -c "python manage.py migrate
             python manage.py collectstatic --no-input
             gunicorn main.wsgi:application -c gunicorn.conf.py"

    env_file:
      - .env.prod
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
